### ISSUE TITLE
how to easy change ui and generate go code

### ISSUE THREAD

**Issue by ddkwork** [andydotxyz/fynebuilder#14]
how to drag container or widget,add or delete from item,edit tree node,inser container with layout,save ui to json or xml,generate ui to go code etc.

![Screenshot_20210419_100146_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/115171922-bee4d980-a0f6-11eb-868b-0cf42287075c.jpg)

**Comment by andydotxyz** [comment]
We are working on exporting code in #13. The other features you mention are on the todo list.
This project is very early in development, but PRs are welcome.

**Comment by andydotxyz** [comment]
I'm going to close this issue as it does not ask a specific question or report an unknown bug.
If you want to track individual items please open specific issues.
