### ISSUE TITLE
Save as "app"

### ISSUE THREAD

**Issue by prifre** [andydotxyz/fynebuilder#15]
possibility to SAVE a skeleton app-code, if you add the standard events too, or somehow have a settings dialog where what is wanted in the skeleton app is selected, than it would become a nice app-builder...

**Comment by andydotxyz** [comment]
I think this is already being worked on at #13.
I didn't want to export an entire application, instead outputting a file with `makeUI` entry point so that in the future this file could be edited without overwriting application code.

**Comment by andydotxyz** [comment]
#13 is in and I have also changed it so the "run" button runs a complete app.
The printing of code has moved to a "download" button... Should we add a third to export the full app as requested in this issue?

**Comment by andydotxyz** [comment]
I think I will mark this as resolved - because the full-app side of things will be managed by Defyne in the future, so saving the UI code should be enough here.
