### ISSUE TITLE
Containers within containers does not work (for me at least)

### ISSUE THREAD

**Issue by prifre** [andydotxyz/fynebuilder#17]
Tested on Windows 10. When a container is selected, most widgets can be added without problem. But containers generate no response...

**Comment by andydotxyz** [comment]
I managed to build this after the bugfix landed:

![Screenshot 2021-05-24 at 09 50 43](https://user-images.githubusercontent.com/294436/119327027-7337c980-bc7a-11eb-8817-bf27420358ea.png)

**Comment by prifre** [comment]
Works great not!

**Comment by prifre** [comment]
Works great now!
